// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sua_isale_default_valuegjhjh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sua_isale_default_valuegjhjh));
        
        string IMigrationMetadata.Id
        {
            get { return "201902200342535_sua_isale_default_valuegjhjh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
