// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addusername_in_user_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addusername_in_user_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201902170311546_add username_in_user_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
